name: Vanish
main: com.echo28.bukkit.vanish.Vanish
version: 1.3.4
commands:
  vanish:
    description: Toggles your visibility
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles your visibility
           /<command> list - List of invisible players