name: Vanish
main: com.echo28.bukkit.vanish.VanishPlugin
version: 1.3
commands:
  vanish:
    description: Toggles your visibility
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles your visibility
           /<command> list - List of invisible players