name: VanishNoPickup
main: com.nilla.vanishnopickup.VanishNoPickup
version: 2.0.0
authors: [EvilNilla, Acrobot]
commands:
  vanish:
    description: Toggles your visibility
    aliases: [poof]
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles your visibility
           /<command> list - List of invisible players
  nopickup:
    description: Toggles Picking Up Items
    aliases: np
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles Your Ability to Pickup Items
           /<command> list - List of players with Item Pickup Disabled